spring.application.name=usuario-service

#Puerto de la aplicación
server.port=0

# Configuración de la conexión (MySQL Local)
spring.datasource.url=jdbc:postgresql://usuarios-db:5432/elbuensabor_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Recomendado para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka client
eureka.client.service-url.defaultZone=http://discovery:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.appname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}:${random.number}

# Enable displaying Actuator endpoints in the OpenAPI documentation
springdoc.show-actuator=true

# Expose 'openapi' and 'swagger-ui' endpoints under the /actuator base path
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui
