spring.application.name=reservas-service

# Puerto aleatorio (correcto para Eureka)
server.port=0

# MySQL (POR NOMBRE DEL SERVICIO)
spring.datasource.url=jdbc:mysql://reservas-db:3306/elbuensabor_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka (POR NOMBRE DEL SERVICIO)
eureka.client.service-url.defaultZone=http://discovery:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.appname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}:${random.value}

springdoc.show-actuator=true
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui
